### ISSUE TITLE
Need a responsive header

### ISSUE THREAD

**Issue by yashsehgal** [Free-Pustakalya/freepustakalya.website#1]
The header is not responsive as of now, we want a hamburger menu for the header component for the mobile/tablet users.
Right now, The header before and after testing the responsiveness is looking like this.

- Desktop View
![image](https://user-images.githubusercontent.com/62352288/123000003-987c3c80-d3cc-11eb-89b4-7b6d1606ea70.png)

- Mobile/Tablet View
![image](https://user-images.githubusercontent.com/62352288/123000074-b34eb100-d3cc-11eb-8b18-19654e5b048f.png)
![image](https://user-images.githubusercontent.com/62352288/123000097-bd70af80-d3cc-11eb-9746-ef55005e8344.png)

Test this in the github-pages test deployment [here](https://free-pustakalya.github.io/freepustakalya.website/#/)

**Comment by deeola** [comment]
Hello, I would love to work on this.

**Comment by badjatya** [comment]
Hey, I would love to make the header responsive and add a hamburger menu for smaller devices.

**Comment by yashsehgal** [comment]
I am assigning this issue to @deeola as of now. @badjatya you can try next time for other issues (there will be more for sure).

**Comment by deeola** [comment]
Hello @yashsehgal, are you aware all components files are empty? Even the App.js file is empty too.

**Comment by yashsehgal** [comment]
The code is on the `development` branch :)

**Comment by deeola** [comment]
Hi, @yashsehgal, I was able to clone the developement branch now and i found it. However, i was not able to run yarn start and i made sure i was in the project directory. package.json was there but it just keeps bouncing back. is this something you need to fix?

**Comment by yashsehgal** [comment]
Nope @deeola everything is working at my end. Try running `npm start`

**Comment by sibteali786** [comment]
Can I work on the issue as it is open and here is no progress even after two months. Also i have few suggestions on improving website . All of these are my opinions 
1. Donate button should be on opposite side of navbar elements(Its just an opinion) and we may add an animation to make it more call to action or attractive. 
2. There is an overflow in horizontal axis as shown in picture. Its not margin because button has none 
![Issue1](https://user-images.githubusercontent.com/62849614/132287101-6d030dd3-e88d-4354-aff9-dbe3a655c533.png)

3. There should be some margin on right side of Donate Button without causing overflow .
